# Generated by Django 6.1 on 2026-10-02 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_renombrar_modelos_a_espanol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'verbose_name': 'carro de abastecimiento', 'verbose_name_plural': 'carros de abastecimiento'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterModelOptions(
            name='despacho',
            options={'verbose_name': 'despacho', 'verbose_name_plural': 'despachos'},
        ),
        migrations.AlterModelOptions(
            name='detallesolicitud',
            options={'verbose_name': 'detalle de solicitud', 'verbose_name_plural': 'detalles de solicitud'},
        ),
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ['commercial_name', 'lot_number'], 'verbose_name': 'insumo', 'verbose_name_plural': 'insumos'},
        ),
        migrations.AlterModelOptions(
            name='itemcarro',
            options={'verbose_name': 'ítem del carro', 'verbose_name_plural': 'ítems del carro'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'solicitud de abastecimiento', 'verbose_name_plural': 'solicitudes de abastecimiento'},
        ),
        migrations.AlterField(
            model_name='carro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('INSTITUCION_MEDICA', 'Institución médica'), ('GESTOR_BODEGA', 'Gestor de bodega')], default='INSTITUCION_MEDICA', max_length=24, verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='academic.solicitud', verbose_name='solicitud'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='commercial_name',
            field=models.CharField(max_length=150, verbose_name='nombre comercial'),
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='lot_number',
            field=models.CharField(max_length=80, verbose_name='número de lote'),
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academic.solicitud', verbose_name='solicitud'),
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='price_per_box',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio por caja'),
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='quantity_boxes',
            field=models.PositiveIntegerField(verbose_name='cantidad de cajas'),
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='academic.insumo', verbose_name='insumo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='active_ingredient',
            field=models.CharField(max_length=150, verbose_name='principio activo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='academic.categoria', verbose_name='categoría'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='commercial_name',
            field=models.CharField(max_length=150, verbose_name='nombre comercial'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='expiration_date',
            field=models.DateField(verbose_name='fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='lot_number',
            field=models.CharField(max_length=80, verbose_name='número de lote'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='price_per_box',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio por caja'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_boxes',
            field=models.PositiveIntegerField(default=0, verbose_name='cajas disponibles'),
        ),
        migrations.AlterField(
            model_name='itemcarro',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academic.carro', verbose_name='carro'),
        ),
        migrations.AlterField(
            model_name='itemcarro',
            name='quantity_boxes',
            field=models.PositiveIntegerField(verbose_name='cantidad de cajas'),
        ),
        migrations.AlterField(
            model_name='itemcarro',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='academic.insumo', verbose_name='insumo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=12, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='institución'),
        ),
    ]
