# Generated by Django 6.1 on 2026-10-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_carro_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('INSTITUCION_MEDICA', 'Cliente'), ('GESTOR_BODEGA', 'Gestor de bodega')], default='INSTITUCION_MEDICA', max_length=24, verbose_name='rol'),
        ),
    ]
