"""
Django settings for mi_proyecto project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

"""Configuración global: aplicaciones, seguridad, PostgreSQL, idioma y API."""

from pathlib import Path
import os

# Ruta absoluta del proyecto; sirve para ubicar plantillas y recursos estáticos.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Las variables de entorno pueden reemplazar los valores locales por defecto;
# para desplegar, configura claves y credenciales propias fuera del repositorio.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-local-development-only-change-before-deploy',
)

# DEBUG y ALLOWED_HOSTS son ajustes de despliegue que deben revisarse en producción.
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', 'testserver']


# Aplicaciones de Django, la API REST, filtros y documentación OpenAPI.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'insumos_medicos.apps.AcademicConfig',
]

# Capas HTTP que gestionan seguridad, sesión, CSRF, autenticación y mensajes.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'farmacia_projecto.urls'

# Motor de plantillas HTML y datos compartidos con todas las páginas.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'insumos_medicos.context_processors.cart_context',
                'insumos_medicos.context_processors.student_footer',
            ],
        },
    },
]

WSGI_APPLICATION = 'farmacia_projecto.wsgi.application'


# PostgreSQL es el motor activo del proyecto. Las variables de entorno permiten
# configurar servidor y credenciales por entorno sin cambiar el código fuente.
# Los valores predeterminados son solo para desarrollo local.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'bd_farmacia'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'Inacap.2030'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Validadores aplicados por Django a contraseñas definidas mediante formularios.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Idioma, zona horaria y soporte de traducción/fechas locales.
LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Ubicación del CSS y otros recursos estáticos propios.
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


# Configuración base de DRF: valida Bearer JWT, exige sesión autenticada salvo
# que una vista declare explícitamente AllowAny y habilita filtros y OpenAPI.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # Las vistas pueden permitir acceso público o restringirlo por rol.
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Título y metadatos expuestos por la documentación Swagger/OpenAPI.
SPECTACULAR_SETTINGS = {
    'TITLE': 'API de Abastecimiento de Insumos Médicos',
    'DESCRIPTION': (
        'API B2B para catálogo, solicitudes, inventario y despacho '
        'de insumos médicos.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# El procesador student_footer los comparte con las plantillas; el año se
# renderiza dinámicamente desde la plantilla base.
STUDENT_NAME = 'Maximiliano Solis'
COURSE_SECTION = 'AP-N4-C1'


# Durante desarrollo, el correo se imprime en consola en lugar de enviarse.
MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
AUTH_USER_MODEL = 'academic.CustomUser'
